name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GCP_SA_EMAIL: ${{ secrets.WA_STAGE_GCP_SA_EMAIL }}
  GCP_SA_KEY: ${{ secrets.WA_STAGE_GCP_SA_KEY }}
  GCP_PROJECT: ${{ secrets.WA_STAGE_GCP_PROJECT_ID }}

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: deploy to app-engine
      uses: google-github-actions/deploy-appengine@v0.4.0
      with:
        deliverables: app.yaml
        project_id: ${{ env.GCP_PROJECT }}
        service_account_key: ${{ env.GCP_SA_KEY }}
        export_default_credentials: true